# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchsong():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchsong(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1193, 795)
    self.driver.find_element(By.ID, "email-address").send_keys("abhinavshashank008@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Admin123")
    self.driver.find_element(By.CSS_SELECTOR, "div > button").click()
    self.driver.find_element(By.LINK_TEXT, "Search Song").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("Happy")
    self.driver.find_element(By.CSS_SELECTOR, ".main_content button").click()
    self.driver.find_element(By.CSS_SELECTOR, "ul > div").click()
    self.driver.find_element(By.CSS_SELECTOR, "ul > div").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "ul > div").text == "Happy Together by The Turtles\\\\n▶ 🎵"
    self.driver.close()
  
