# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMysongs():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mysongs(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1193, 795)
    self.driver.find_element(By.ID, "email-address").send_keys("abhinavshashank008@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Admin123")
    self.driver.find_element(By.CSS_SELECTOR, "div > button").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'My Songs\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".song-buttons > button:nth-child(1)")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".song-buttons > button:nth-child(1)").text == "▶"

