# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUsercreate():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_usercreate(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1388, 1000)
    self.driver.find_element(By.CSS_SELECTOR, ".text-blue-500 > button").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > input").send_keys("anyemail@mail.com")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > input").send_keys("1234567")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".sidebar")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".sidebar")
    assert len(elements) > 0
  
