# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("http://localhost:3000/")
    self.driver.maximize_window()
    self.driver.find_element(By.ID, "email-address").send_keys("abhinavshashank008@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Admin123")
    self.driver.find_element(By.CSS_SELECTOR, "div > button").click()
    time.sleep(3)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".sidebar")
    assert len(elements) > 0
    time.sleep(3)
    # WebDriverWait(self.driver, 30).until(expected_conditions.text_to_be_present_in_element((By.CSS_SELECTOR, ".main_content:nth-child(1) > div > div"), "rock you by queen\\n▶ 🎵"))
    # WebDriverWait(self.driver, 5).until(expected_conditions.text_to_be_present_in_element((By.XPATH, "//div[@id='root']/div/div[2]/div/div/div"), "rock you by queen\\n▶ 🎵"))
    self.driver.find_element(By.LINK_TEXT, "Search Song").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("rock")
    self.driver.find_element(By.CSS_SELECTOR, ".main_content > div > button").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "ul > div").text == "rock you by queen\\\\n▶ 🎵"
  
