# Generated by Selenium IDEL
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginlogout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginlogout(self):
    self.driver.get("http://localhost:3000/")
    self.driver.maximize_window()
    self.driver.find_element(By.ID, "email-address").send_keys("michael.dannyboy@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("password")
    time.sleep(3)
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//button[contains(.,\'Log In\')]"))).click()
    # self.driver.find_element(By.XPATH, "//button[contains(.,\'Log In\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".sidebar")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".sidebar")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Sign Out").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//h1[contains(.,\'MusiCloud\')]")))
    elements = self.driver.find_elements(By.XPATH, "//h1[contains(.,\'MusiCloud\')]")
    assert len(elements) > 0
  
